import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateYugiohModule1760000000000 implements MigrationInterface {
  name = 'CreateYugiohModule1760000000000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TYPE "public"."yugioh_leagues_format_enum" AS ENUM('GOAT','EDISON','ADVANCED','SPEED_DUEL','OTHER')`);
    await q.query(`CREATE TYPE "public"."yugioh_leagues_status_enum" AS ENUM('DRAFT','ACTIVE','FINISHED')`);
    await q.query(`CREATE TYPE "public"."yugioh_players_status_enum" AS ENUM('ACTIVE','INACTIVE','RETIRED')`);
    await q.query(`CREATE TYPE "public"."yugioh_league_participants_status_enum" AS ENUM('ACTIVE','INACTIVE','RETIRED')`);
    await q.query(`CREATE TYPE "public"."yugioh_rounds_status_enum" AS ENUM('DRAFT','IN_PROGRESS','COMPLETED')`);
    await q.query(`CREATE TYPE "public"."yugioh_matches_status_enum" AS ENUM('PENDING','COMPLETED')`);
    await q.query(`CREATE TYPE "public"."yugioh_league_staff_role_enum" AS ENUM('ADMIN','STAFF')`);
    await q.query(`CREATE TABLE "yugioh_leagues" ("id" SERIAL NOT NULL, "name" varchar(120) NOT NULL, "slug" varchar(140) NOT NULL, "description" text NOT NULL DEFAULT '', "format" "public"."yugioh_leagues_format_enum" NOT NULL, "season" varchar(80) NOT NULL, "status" "public"."yugioh_leagues_status_enum" NOT NULL DEFAULT 'DRAFT', "scoringConfig" jsonb NOT NULL DEFAULT '{"winPoints":3,"drawPoints":1,"lossPoints":0,"byePoints":3,"allowDraws":true,"validScores":["2-0","2-1","1-2","0-2","1-1"]}'::jsonb, "pairingConfig" jsonb NOT NULL DEFAULT '{"avoidRematches":true,"avoidRepeatedByes":true}'::jsonb, "createdByUserId" integer NOT NULL, "finishedAt" TIMESTAMPTZ, "finalPodium" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_yugioh_leagues_slug" UNIQUE ("slug"), CONSTRAINT "PK_yugioh_leagues" PRIMARY KEY ("id"), CONSTRAINT "FK_yugioh_league_creator" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await q.query(`CREATE TABLE "yugioh_players" ("id" SERIAL NOT NULL, "name" varchar(100) NOT NULL, "nickname" varchar(80), "status" "public"."yugioh_players_status_enum" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_yugioh_players" PRIMARY KEY ("id"))`);
    await q.query(`CREATE TABLE "yugioh_league_participants" ("id" SERIAL NOT NULL, "leagueId" integer NOT NULL, "playerId" integer NOT NULL, "status" "public"."yugioh_league_participants_status_enum" NOT NULL DEFAULT 'ACTIVE', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "retiredAt" TIMESTAMPTZ, CONSTRAINT "UQ_yugioh_participant" UNIQUE ("leagueId","playerId"), CONSTRAINT "PK_yugioh_participants" PRIMARY KEY ("id"), CONSTRAINT "FK_yugioh_participant_league" FOREIGN KEY ("leagueId") REFERENCES "yugioh_leagues"("id") ON DELETE CASCADE, CONSTRAINT "FK_yugioh_participant_player" FOREIGN KEY ("playerId") REFERENCES "yugioh_players"("id") ON DELETE RESTRICT)`);
    await q.query(`CREATE INDEX "IDX_yugioh_participant_league" ON "yugioh_league_participants" ("leagueId"); CREATE INDEX "IDX_yugioh_participant_player" ON "yugioh_league_participants" ("playerId")`);
    await q.query(`CREATE TABLE "yugioh_rounds" ("id" SERIAL NOT NULL, "leagueId" integer NOT NULL, "number" smallint NOT NULL, "status" "public"."yugioh_rounds_status_enum" NOT NULL DEFAULT 'DRAFT', "pairingsConfirmed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "startedAt" TIMESTAMPTZ, "completedAt" TIMESTAMPTZ, CONSTRAINT "UQ_yugioh_round" UNIQUE ("leagueId","number"), CONSTRAINT "PK_yugioh_rounds" PRIMARY KEY ("id"), CONSTRAINT "FK_yugioh_round_league" FOREIGN KEY ("leagueId") REFERENCES "yugioh_leagues"("id") ON DELETE CASCADE)`);
    await q.query(`CREATE UNIQUE INDEX "UQ_yugioh_one_open_round" ON "yugioh_rounds" ("leagueId") WHERE "status" <> 'COMPLETED'; CREATE INDEX "IDX_yugioh_round_league" ON "yugioh_rounds" ("leagueId")`);
    await q.query(`CREATE TABLE "yugioh_matches" ("id" SERIAL NOT NULL, "roundId" integer NOT NULL, "tableNumber" smallint NOT NULL, "playerAId" integer NOT NULL, "playerBId" integer, "playerAScore" smallint, "playerBScore" smallint, "winnerId" integer, "status" "public"."yugioh_matches_status_enum" NOT NULL DEFAULT 'PENDING', "isBye" boolean NOT NULL DEFAULT false, "isAdministrative" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMPTZ, "reportedByUserId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_yugioh_match_table" UNIQUE ("roundId","tableNumber"), CONSTRAINT "CHK_yugioh_match_players" CHECK ("playerAId" <> "playerBId"), CONSTRAINT "CHK_yugioh_match_bye" CHECK (("isBye" = false AND "playerBId" IS NOT NULL) OR ("isBye" = true AND "playerBId" IS NULL)), CONSTRAINT "PK_yugioh_matches" PRIMARY KEY ("id"), CONSTRAINT "FK_yugioh_match_round" FOREIGN KEY ("roundId") REFERENCES "yugioh_rounds"("id") ON DELETE CASCADE, CONSTRAINT "FK_yugioh_match_a" FOREIGN KEY ("playerAId") REFERENCES "yugioh_league_participants"("id") ON DELETE RESTRICT, CONSTRAINT "FK_yugioh_match_b" FOREIGN KEY ("playerBId") REFERENCES "yugioh_league_participants"("id") ON DELETE RESTRICT, CONSTRAINT "FK_yugioh_match_winner" FOREIGN KEY ("winnerId") REFERENCES "yugioh_league_participants"("id") ON DELETE RESTRICT, CONSTRAINT "FK_yugioh_match_reporter" FOREIGN KEY ("reportedByUserId") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await q.query(`CREATE INDEX "IDX_yugioh_match_round" ON "yugioh_matches" ("roundId")`);
    await q.query(`CREATE TABLE "yugioh_league_staff" ("id" SERIAL NOT NULL, "leagueId" integer NOT NULL, "userId" integer NOT NULL, "role" "public"."yugioh_league_staff_role_enum" NOT NULL, CONSTRAINT "UQ_yugioh_staff" UNIQUE ("leagueId","userId"), CONSTRAINT "PK_yugioh_staff" PRIMARY KEY ("id"), CONSTRAINT "FK_yugioh_staff_league" FOREIGN KEY ("leagueId") REFERENCES "yugioh_leagues"("id") ON DELETE CASCADE, CONSTRAINT "FK_yugioh_staff_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE)`);
    await q.query(`CREATE INDEX "IDX_yugioh_staff_league" ON "yugioh_league_staff" ("leagueId"); CREATE INDEX "IDX_yugioh_staff_user" ON "yugioh_league_staff" ("userId")`);
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE "yugioh_league_staff"; DROP TABLE "yugioh_matches"; DROP TABLE "yugioh_rounds"; DROP TABLE "yugioh_league_participants"; DROP TABLE "yugioh_players"; DROP TABLE "yugioh_leagues"`);
    await q.query(`DROP TYPE "public"."yugioh_league_staff_role_enum"; DROP TYPE "public"."yugioh_matches_status_enum"; DROP TYPE "public"."yugioh_rounds_status_enum"; DROP TYPE "public"."yugioh_league_participants_status_enum"; DROP TYPE "public"."yugioh_players_status_enum"; DROP TYPE "public"."yugioh_leagues_status_enum"; DROP TYPE "public"."yugioh_leagues_format_enum"`);
  }
}
