import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, In, Repository } from 'typeorm';
import { AddParticipantDto, AddStaffDto, CreateLeagueDto, ReplacePairingsDto, ResultDto, UpdateLeagueDto, UpdateParticipantDto } from './dto/yugioh.dto';
import { YugiohLeague } from './entities/yugioh-league.entity';
import { YugiohMatch } from './entities/yugioh-match.entity';
import { YugiohLeagueParticipant } from './entities/yugioh-participant.entity';
import { YugiohPlayer } from './entities/yugioh-player.entity';
import { YugiohRound } from './entities/yugioh-round.entity';
import { YugiohLeagueStaff } from './entities/yugioh-staff.entity';
import { PairingCandidate, PairingsService } from './pairings.service';
import { StandingsService } from './standings.service';
import { DEFAULT_PAIRING, DEFAULT_SCORING, YugiohLeagueStatus, YugiohMatchStatus, YugiohPlayerStatus, YugiohRoundStatus, YugiohStaffRole } from './yugioh.enums';

@Injectable()
export class YugiohService {
  constructor(
    private readonly dataSource: DataSource,
    @InjectRepository(YugiohLeague) private readonly leagues: Repository<YugiohLeague>,
    @InjectRepository(YugiohPlayer) private readonly players: Repository<YugiohPlayer>,
    @InjectRepository(YugiohLeagueParticipant) private readonly participants: Repository<YugiohLeagueParticipant>,
    @InjectRepository(YugiohRound) private readonly rounds: Repository<YugiohRound>,
    @InjectRepository(YugiohMatch) private readonly matches: Repository<YugiohMatch>,
    @InjectRepository(YugiohLeagueStaff) private readonly staff: Repository<YugiohLeagueStaff>,
    private readonly pairings: PairingsService,
    private readonly standingsCalculator: StandingsService,
  ) {}

  listLeagues() { return this.leagues.find({ order: { createdAt: 'DESC' } }); }
  async getLeague(id: number) { const league = await this.leagues.findOne({ where: { id }, relations: { participants: { player: true }, rounds: true } }); if (!league) throw new NotFoundException('Liga no encontrada'); return league; }
  async createLeague(userId: number, dto: CreateLeagueDto) {
    return this.dataSource.transaction(async manager => {
      const base = this.slug(dto.name); let slug = base; let suffix = 2;
      while (await manager.existsBy(YugiohLeague, { slug })) slug = `${base}-${suffix++}`;
      const league = await manager.save(manager.create(YugiohLeague, { ...dto, name: dto.name.trim(), description: dto.description?.trim() ?? '', season: dto.season.trim(), slug, createdByUserId: userId, scoringConfig: dto.scoringConfig ?? DEFAULT_SCORING, pairingConfig: DEFAULT_PAIRING }));
      await manager.save(manager.create(YugiohLeagueStaff, { leagueId: league.id, userId, role: YugiohStaffRole.ADMIN }));
      return league;
    });
  }
  async updateLeague(userId: number, id: number, dto: UpdateLeagueDto) { await this.requireRole(userId, id, [YugiohStaffRole.ADMIN]); const league = await this.getLeagueEntity(id); if (dto.scoringConfig && league.status !== YugiohLeagueStatus.DRAFT) throw new ConflictException('La puntuación sólo puede cambiarse mientras la liga está en borrador'); Object.assign(league, dto); return this.leagues.save(league); }
  async reopen(userId: number, id: number) { await this.requireRole(userId, id, [YugiohStaffRole.ADMIN]); const league = await this.getLeagueEntity(id); if (league.status !== YugiohLeagueStatus.FINISHED) throw new ConflictException('La liga no está finalizada'); league.status = YugiohLeagueStatus.ACTIVE; league.finishedAt = null; league.finalPodium = null; return this.leagues.save(league); }
  async finish(userId: number, id: number) { await this.requireRole(userId, id, [YugiohStaffRole.ADMIN]); const pending = await this.rounds.count({ where: { leagueId: id, status: In([YugiohRoundStatus.DRAFT, YugiohRoundStatus.IN_PROGRESS]) } }); if (pending) throw new ConflictException('No se puede finalizar con jornadas pendientes'); const standings = await this.getStandings(id); if (!standings.length) throw new ConflictException('La liga no tiene participantes'); const league = await this.getLeagueEntity(id); league.status = YugiohLeagueStatus.FINISHED; league.finishedAt = new Date(); league.finalPodium = { championId: standings[0].playerId, runnerUpId: standings[1]?.playerId, thirdId: standings[2]?.playerId }; return this.leagues.save(league); }

  listParticipants(leagueId: number) { return this.participants.find({ where: { leagueId }, relations: { player: true }, order: { joinedAt: 'ASC' } }); }
  async addParticipant(userId: number, leagueId: number, dto: AddParticipantDto) { await this.requireRole(userId, leagueId, [YugiohStaffRole.ADMIN]); const league = await this.getLeagueEntity(leagueId); if (league.status === YugiohLeagueStatus.FINISHED) throw new ConflictException('La liga está finalizada'); let player: YugiohPlayer | null = null; if (dto.playerId) player = await this.players.findOneBy({ id: dto.playerId }); else if (dto.name) player = await this.players.save(this.players.create({ name: dto.name.trim(), nickname: dto.nickname?.trim() || null })); if (!player) throw new BadRequestException('Indica playerId o los datos del jugador'); if (await this.participants.existsBy({ leagueId, playerId: player.id })) throw new ConflictException('El jugador ya participa en esta liga'); return this.participants.save(this.participants.create({ leagueId, playerId: player.id, status: YugiohPlayerStatus.ACTIVE })); }
  async updateParticipant(userId: number, leagueId: number, participantId: number, dto: UpdateParticipantDto) { await this.requireRole(userId, leagueId, [YugiohStaffRole.ADMIN]); const participant = await this.participants.findOneBy({ id: participantId, leagueId }); if (!participant) throw new NotFoundException('Participante no encontrado'); participant.status = dto.status; participant.retiredAt = dto.status === YugiohPlayerStatus.RETIRED ? new Date() : null; return this.participants.save(participant); }

  listRounds(leagueId: number) { return this.rounds.find({ where: { leagueId }, relations: { matches: { playerA: { player: true }, playerB: { player: true } } }, order: { number: 'DESC' } }); }
  async getRound(id: number) { const round = await this.rounds.findOne({ where: { id }, relations: { matches: { playerA: { player: true }, playerB: { player: true } } } }); if (!round) throw new NotFoundException('Jornada no encontrada'); return round; }
  async createRound(userId: number, leagueId: number) { await this.requireRole(userId, leagueId, [YugiohStaffRole.ADMIN]); return this.dataSource.transaction('SERIALIZABLE', async manager => { const league = await manager.getRepository(YugiohLeague).createQueryBuilder('league').setLock('pessimistic_write').where('league.id = :leagueId', { leagueId }).getOne(); if (!league) throw new NotFoundException('Liga no encontrada'); if (league.status === YugiohLeagueStatus.FINISHED) throw new ConflictException('La liga está finalizada'); const open = await manager.exists(YugiohRound, { where: { leagueId, status: In([YugiohRoundStatus.DRAFT, YugiohRoundStatus.IN_PROGRESS]) } }); if (open) throw new ConflictException('Ya existe una jornada sin completar'); const count = await manager.count(YugiohLeagueParticipant, { where: { leagueId, status: YugiohPlayerStatus.ACTIVE } }); if (count < 2) throw new ConflictException('Se requieren al menos dos participantes activos'); const number = (await manager.maximum(YugiohRound, 'number', { leagueId }) ?? 0) + 1; if (league.status === YugiohLeagueStatus.DRAFT) { league.status = YugiohLeagueStatus.ACTIVE; await manager.save(league); } return manager.save(manager.create(YugiohRound, { leagueId, number })); }); }
  async generatePairings(userId: number, roundId: number) { const round = await this.getRoundEntity(roundId); await this.requireRole(userId, round.leagueId, [YugiohStaffRole.ADMIN]); if (round.pairingsConfirmed) throw new ConflictException('Los pareos ya están confirmados'); const candidates = await this.pairingCandidates(round.leagueId); const proposal = this.pairings.generate(candidates); await this.dataSource.transaction(async manager => { await manager.delete(YugiohMatch, { roundId }); await manager.save(proposal.map((p, index) => manager.create(YugiohMatch, { roundId, tableNumber: index + 1, ...p, status: p.isBye ? YugiohMatchStatus.COMPLETED : YugiohMatchStatus.PENDING, playerAScore: p.isBye ? 2 : null, playerBScore: p.isBye ? 0 : null, winnerId: p.isBye ? p.playerAId : null, completedAt: p.isBye ? new Date() : null }))); }); return this.getRound(roundId); }
  async replacePairings(userId: number, roundId: number, dto: ReplacePairingsDto) { const round = await this.getRoundEntity(roundId); await this.requireRole(userId, round.leagueId, [YugiohStaffRole.ADMIN]); if (round.pairingsConfirmed) throw new ConflictException('Los pareos ya están confirmados'); const active = new Set((await this.participants.findBy({ leagueId: round.leagueId, status: YugiohPlayerStatus.ACTIVE })).map(p => p.id)); const used = new Set<number>(); for (const pairing of dto.pairings) { if (!active.has(pairing.playerAId) || (pairing.playerBId && !active.has(pairing.playerBId))) throw new BadRequestException('El pareo contiene participantes inactivos o ajenos'); if (pairing.playerAId === pairing.playerBId || used.has(pairing.playerAId) || (pairing.playerBId && used.has(pairing.playerBId))) throw new BadRequestException('Un participante no puede repetirse ni enfrentarse consigo mismo'); used.add(pairing.playerAId); if (pairing.playerBId) used.add(pairing.playerBId); } if (used.size !== active.size) throw new BadRequestException('Todos los participantes activos deben aparecer exactamente una vez'); await this.dataSource.transaction(async manager => { await manager.delete(YugiohMatch, { roundId }); await manager.save(dto.pairings.map((p, i) => { const isBye = !p.playerBId; return manager.create(YugiohMatch, { roundId, tableNumber: i + 1, playerAId: p.playerAId, playerBId: p.playerBId ?? null, isBye, status: isBye ? YugiohMatchStatus.COMPLETED : YugiohMatchStatus.PENDING, playerAScore: isBye ? 2 : null, playerBScore: isBye ? 0 : null, winnerId: isBye ? p.playerAId : null, completedAt: isBye ? new Date() : null }); })); }); return this.getRound(roundId); }
  async confirmPairings(userId: number, roundId: number) { const round = await this.getRoundEntity(roundId); await this.requireRole(userId, round.leagueId, [YugiohStaffRole.ADMIN]); return this.dataSource.transaction(async manager => { const locked = await manager.getRepository(YugiohRound).createQueryBuilder('round').setLock('pessimistic_write').where('round.id = :roundId', { roundId }).getOneOrFail(); if (locked.pairingsConfirmed) throw new ConflictException('Los pareos ya están confirmados'); if (!(await manager.count(YugiohMatch, { where: { roundId } }))) throw new ConflictException('Primero genera los pareos'); locked.pairingsConfirmed = true; locked.status = YugiohRoundStatus.IN_PROGRESS; locked.startedAt = new Date(); return manager.save(locked); }); }
  async reportResult(userId: number, matchId: number, dto: ResultDto) { const match = await this.matches.findOne({ where: { id: matchId }, relations: { round: { league: true } } }); if (!match) throw new NotFoundException('Enfrentamiento no encontrado'); await this.requireRole(userId, match.round.leagueId, [YugiohStaffRole.ADMIN, YugiohStaffRole.STAFF]); if (!match.round.pairingsConfirmed) throw new ConflictException('Los pareos no están confirmados'); if (match.isBye) throw new ConflictException('Un BYE se resuelve automáticamente'); const score = `${dto.playerAScore}-${dto.playerBScore}`; const config = match.round.league.scoringConfig; if (!config.validScores.includes(score) || (!config.allowDraws && dto.playerAScore === dto.playerBScore)) throw new BadRequestException('Marcador no permitido por la configuración de la liga'); return this.dataSource.transaction(async manager => { const locked = await manager.getRepository(YugiohMatch).createQueryBuilder('match').setLock('pessimistic_write').where('match.id = :matchId', { matchId }).getOneOrFail(); locked.playerAScore = dto.playerAScore; locked.playerBScore = dto.playerBScore; locked.winnerId = dto.playerAScore === dto.playerBScore ? null : dto.playerAScore > dto.playerBScore ? locked.playerAId : locked.playerBId; locked.status = YugiohMatchStatus.COMPLETED; locked.isAdministrative = dto.administrative ?? false; locked.reportedByUserId = userId; locked.completedAt = new Date(); await manager.save(locked); await this.completeRoundIfReady(manager, locked.roundId); return locked; }); }
  async getStandings(leagueId: number) { const league = await this.getLeagueEntity(leagueId); const participants = await this.listParticipants(leagueId); const matches = await this.matches.createQueryBuilder('match').innerJoin('match.round', 'round', 'round.leagueId = :leagueId', { leagueId }).getMany(); return this.standingsCalculator.calculate(participants, matches, league.scoringConfig); }
  async playerProfile(playerId: number) { const player = await this.players.findOneBy({ id: playerId }); if (!player) throw new NotFoundException('Jugador no encontrado'); const participations = await this.participants.find({ where: { playerId }, relations: { league: true } }); const ids = participations.map(p => p.id); const matches = ids.length ? await this.matches.find({ where: [{ playerAId: In(ids) }, { playerBId: In(ids) }], relations: { round: true, playerA: { player: true }, playerB: { player: true } }, order: { createdAt: 'DESC' } }) : []; return { player, participations, matches }; }
  async addStaff(userId: number, leagueId: number, dto: AddStaffDto) { await this.requireRole(userId, leagueId, [YugiohStaffRole.ADMIN]); const existing = await this.staff.findOneBy({ leagueId, userId: dto.userId }); if (existing) { existing.role = dto.role; return this.staff.save(existing); } return this.staff.save(this.staff.create({ leagueId, userId: dto.userId, role: dto.role })); }
  async exportLeague(userId: number, leagueId: number) { await this.requireRole(userId, leagueId, [YugiohStaffRole.ADMIN]); const league = await this.getLeague(leagueId); const rounds = await this.listRounds(leagueId); return { schemaVersion: 1, exportedAt: new Date().toISOString(), league: { ...league, participants: undefined, rounds: undefined }, participants: league.participants, rounds: rounds.map(({ matches, ...round }) => round), matches: rounds.flatMap(round => round.matches) }; }

  private async requireRole(userId: number, leagueId: number, roles: YugiohStaffRole[]) { const member = await this.staff.findOneBy({ leagueId, userId }); if (!member || !roles.includes(member.role)) throw new ForbiddenException('No tienes permisos para administrar esta liga'); return member; }
  private async getLeagueEntity(id: number) { const league = await this.leagues.findOneBy({ id }); if (!league) throw new NotFoundException('Liga no encontrada'); return league; }
  private async getRoundEntity(id: number) { const round = await this.rounds.findOneBy({ id }); if (!round) throw new NotFoundException('Jornada no encontrada'); return round; }
  private async pairingCandidates(leagueId: number): Promise<PairingCandidate[]> { const active = await this.participants.find({ where: { leagueId, status: YugiohPlayerStatus.ACTIVE }, relations: { player: true } }); const standings = await this.getStandings(leagueId); const completed = await this.matches.createQueryBuilder('match').innerJoin('match.round', 'round', 'round.leagueId = :leagueId', { leagueId }).where('match.status = :status', { status: YugiohMatchStatus.COMPLETED }).getMany(); return active.map(p => ({ id: p.id, points: standings.find(s => s.participantId === p.id)?.points ?? 0, opponents: completed.filter(m => m.playerAId === p.id || m.playerBId === p.id).flatMap(m => [m.playerAId, m.playerBId].filter((id): id is number => !!id && id !== p.id)), byes: completed.filter(m => m.isBye && m.playerAId === p.id).length })); }
  private async completeRoundIfReady(manager: EntityManager, roundId: number) { if (await manager.count(YugiohMatch, { where: { roundId, status: YugiohMatchStatus.PENDING } })) return; const round = await manager.findOneByOrFail(YugiohRound, { id: roundId }); round.status = YugiohRoundStatus.COMPLETED; round.completedAt = new Date(); await manager.save(round); }
  private slug(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'liga'; }
}
